---
- name: Ensure minecraft directory is owned by the default user
  file: name={{minecraft_dir}} state=directory owner={{admin_user}} group={{admin_user}}

- name: Ensure minecraft server traffic allowed through firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: '25565'

- name: Ensure minecraft container is started
  docker_container:
    name: minecraft
    image: itzg/minecraft-server
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{minecraft_dir}}:/data"
    ports:
      - "25565:25565/tcp"
    env: "{{ minecraft_server_core | combine(minecraft_server_env) }}"
    command: "--noconsole"

- name: Ensure rcon script is present
  copy:
    src: rcon.sh
    dest: /home/{{user}}/.local/bin/rcon
    mode: 0755
    owner: "{{user}}"
    group: "{{user}}"

