- hosts: all
  tasks:
          - name: Ensure mosh is installed
            apt: name=mosh state=installed

          - name: Ensure vim is installed
            apt: name=vim state=installed

          - name: Ensure tmux is installed
            apt: name=tmux state=installed

          - name: Ensure git is installed
            apt: name=git state=installed

          - name: Ensure zsh is installed
            apt: name=zsh state=installed

          - name: Ensure docker is installed
            apt: name=docker.io state=installed
          
          - name: Add a docker group
            group: name=docker

          - name: Add a non-root user
            user: name=dave groups=sudo,docker shell=/usr/bin/zsh

          - name: Set authorized keys
            authorized_key: user=dave key=https://github.com/dave-burke.keys

          - name: Disable password logins
            lineinfile:
                    dest: /etc/ssh/sshd_config
                    regexp: #?PasswordAuthentication.*
                    line: PasswordAuthentication no

          - name: Clone dotfiles repository
            git: repo=https://github.com/dave-burke/dotfiles.git dest=/home/dave/dotfiles force=yes

          - name: Bootstrap dotfiles
            shell: executable=/home/dave/dotfiles/bootstrap.sh -f creates=/home/dave/.config/mc/lib/mc-solarized-skin

