---
- hosts: all
  tasks:
  - name: Update all packages to the latest version
    apt: upgrade=dist update_cache=yes

  - import_tasks: utils.yml
  - import_tasks: docker.yml
  - import_tasks: user.yml
  - import_tasks: security.yml

