---
- hosts: all
  roles:
    - base

- hosts: compy
  roles:
    - users_dave
    - users_wesley
    - users_andrew
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - servy
          - happy
          - asuz
          - phone
          - tabby
    - development
    - photo_mgmt
    - syncthing
    - budget
    - backup_client
    - aws_cli
    - video_transcoding
  tasks:
    - name: Ensure storage disk is mounted
      tags: ['fstab']
      mount:
        path: "/mnt/storage"
        src: UUID=5f0562d1-ea1b-4d1c-b47d-9587c67a2759
        fstype: ext4
        opts: defaults
        dump: "0"
        passno: "3"
        state: mounted

- hosts: asuz
  roles:
    - users_dave
    - users_suz
    - users_wesley
    - users_andrew
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - servy
          - compy
          - happy
    - syncthing
    - touchpad_toggle
    - backup_client

- hosts: servy
  roles:
    - users_dave
    #- users_suz
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - compy
          - happy
          - asuz
          - phone
          - tabby
    - syncthing
    - raid_storage
    - docker
    - dns
    - reverse_proxy
    - plex
    - minecraft_server
    - backup_server
    - backup_client
    - nfs_server
    - budget_web
    - netmon
    - static_web_host
    #- vpn # TODO copy keys to clients
    #- dyndns_client
    #- torrent
    #- couchdb
  tasks:
    - name: "Ensure {{item}} has access to syncthing GUI"
      tags: ['ufw', 'test']
      ufw:
        comment: 'Syncthing from {{item}}'
        rule: allow
        from_ip: "{{hostvars[item].ansible_host}}"
        port: '8384'
        proto: 'tcp'
      loop: ['compy','happy']
    #- name: "Link to {{item}}"
      #file: src=/mnt/storage/{{item}} dest=/home/{{user}}/{{item}} state=link
      #with_items:
        #- audio
        #- backup
        #- dev
        #- photos
        #- uploads
        #- videos

- hosts: dropy
  roles:
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - compy
          - happy
          - phone
          - tabby
    - role: ssh_command_receiver
      vars:
        user: dave
        action_name: minecraft
        auth_key: ssh/dave/servy/id_rsa_minecraft.pub
        commands:
          - "docker stop minecraft"
          - "docker start minecraft"
    - users_dave
    - jitsi_meet
    - role: minecraft_server
      vars:
        minecraft_server_state: stopped
    - backup_client
    - murmur

- hosts: happy
  tasks:
    - name: Blacklist PC Speaker module
      tags: ['pcspeaker', 'pcspkr']
      copy:
        dest: /etc/modprobe.d/nobeep.conf
        content: "blacklist pcspkr"
  roles:
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - servy
          - phone
          - tabby
          - compy
    - users_dave
    - development
    - syncthing
    - budget
    - role: nfs_client
      vars:
        nfs_mounts:
          - host: servy
            name: photos
            dir: /mnt/nfs/photos

- hosts: nextcloud
  roles:
    - role: ssh_user
      vars:
        user: dave
        authorized_hosts:
          - compy
          - happy
          - phone
          - tabby
    - users_dave
    - role: reverse_proxy
      vars:
        traefik_labels: {}
        traefik_config_dir: "/opt/traefik"
    - nextcloud

