---
- hosts: all
  roles:
    - base
- hosts: asuz
  tasks:
    - import_role:
        name: backup_client
      vars:
        backup_server_host: servy
        backup_client_user: suz
- hosts: servy
  roles:
    - raid_storage
    - dns
    - vpn
    - reverse-proxy
    - plex
    - torrent
    - netmon
    - dyndns_client
    - minecraft_server
    - backup_server
  tasks:
    - name: "Link to {{item}}"
      file: src=/mnt/storage/{{item}} dest=/home/{{user}}/{{item}} state=link
      with_items:
        - audio
        - dev
        - docs
        - photos
        - uploads
        - videos

