---
- hosts: all
  roles:
    - base

- hosts: compy
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - asuz
        - phone
        - tabby
        - pavey
    - minecraft_client

- hosts: asuz
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - compy
    - minecraft_client
    - role: backup_client
      backup_server_host: servy
      backup_client_user: suz

- hosts: servy
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - compy
        - asuz
        - phone
        - tabby
        - pavey
    - raid_storage
    - dns
    - vpn
    - reverse_proxy
    - plex
    - torrent
    - netmon
    - dyndns_client
    - minecraft_server
    - backup_server
    - s3_sync
  tasks:
    - name: "Link to {{item}}"
      file: src=/mnt/storage/{{item}} dest=/home/{{user}}/{{item}} state=link
      with_items:
        - audio
        - dev
        - docs
        - photos
        - uploads
        - videos

