---
- hosts: all
  roles:
    - base

- hosts: compy
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - asuz
        - phone
        - tabby
        - pavey
    - minecraft_client
    - photo-mgmt
    - budget
    - role: backup_client
      backup_server_host: servy
      backup_client_user: dave
      backup_client_dirs:
        - name: home
          dir: "~"
          exclusions:
            - "Desktop/recent_photos"
            - "Desktop/LiftingVids"
            - "Dropbox"
            - ".dropbox"
            - ".dropbox-dist"
            - "Dropbox-tm"
            - ".dropbox-tm"
            - "tmp"
            - ".eclipse"
            - ".gradle"
            - ".Idea"
            - ".local/share/irrationalgames"
            - ".local/share/Steam"
            - ".local/share/Trash"
            - ".local/share/tracker"
            - ".cache"
        - dir: "/mnt/storage/docs"
  tasks:
    - name: Ensure storage disk is mounted
      mount:
        path: "/mnt/storage"
        src: UUID=338a8dd5-3d41-433d-87c7-56a9339fa194
        fstype: ext3
        opts: defaults
        dump: 0
        passno: 3
        state: mounted

- hosts: asuz
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - compy
    - minecraft_client
    - role: backup_client
      backup_server_host: servy
      backup_client_user: suz
      backup_client_dirs:
        - dir: ~/Desktop
          exclusions:
            - "Recent\\ Photos"
        - dir: ~/Documents
        - dir: ~/pics

- hosts: servy
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - compy
        - asuz
        - phone
        - tabby
        - pavey
    - raid_storage
    - dns
    - vpn
    - reverse_proxy
    - plex
    - torrent
    - netmon
    - dyndns_client
    - minecraft_server
    - role: backup_server
    - s3_sync
  tasks:
    - name: "Link to {{item}}"
      file: src=/mnt/storage/{{item}} dest=/home/{{user}}/{{item}} state=link
      with_items:
        - audio
        - dev
        - photos
        - uploads
        - videos

