---
- hosts: all
  roles:
    - base

- hosts: compy
  roles:
    - dave
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - happy
        - asuz
        - phone
        - tabby
    - development
    - photo_mgmt
    - syncthing
    - budget
    - role: backup_client
      backup_server_host: servy
      backup_client_user: dave
      backup_client_dirs:
        - name: home
          dir: "/home/dave"
          exclusions:
            - ".Idea"
            - ".cache"
            - ".config/syncthing/index*db"
            - ".dropbox*"
            - ".eclipse"
            - ".gradle"
            - ".local/share/Steam"
            - ".local/share/Trash"
            - ".local/share/irrationalgames"
            - ".local/share/tracker"
            - "Desktop/LiftingVids"
            - "Desktop/recent_photos"
            - "Downloads"
            - "Dropbox*"
            - "tmp"
        - dir: "/mnt/storage/docs"
  tasks:
    - name: Ensure storage disk is mounted
      mount:
        path: "/mnt/storage"
        src: UUID=338a8dd5-3d41-433d-87c7-56a9339fa194
        fstype: ext3
        opts: defaults
        dump: "0"
        passno: "3"
        state: mounted

- hosts: asuz
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - compy
        - happy
    - syncthing
    - touchpad_toggle
    - role: backup_client
      backup_server_host: servy
      backup_client_user: suz
      backup_client_dirs:
        - dir: /home/suz/Desktop
          exclusions:
            - "Recent Photos"
        - dir: /home/suz/Documents
        - dir: /home/suz/pics

- hosts: servy
  roles:
    - dave
    - role: ssh_user
      user: dave
      authorized_hosts:
        - compy
        - happy
        - asuz
        - phone
        - tabby
    - raid_storage
    - dns
    - vpn
    - reverse_proxy
    - syncthing
    - plex
    - budget_web
    - torrent
    - netmon
    - dyndns_client
    - minecraft_server
    - backup_server
    - s3_sync
    - wasabi_cli
    - nfs_server
  tasks:
    - name: "Ensure {{item}} has access to syncthing GUI"
      tags: ['ufw', 'test']
      ufw:
        comment: 'Syncthing from {{item}}'
        rule: allow
        from_ip: "{{hostvars[item].ansible_host}}"
        port: '8384'
        proto: 'tcp'
      loop: ['compy','happy']
    - name: "Link to {{item}}"
      file: src=/mnt/storage/{{item}} dest=/home/{{user}}/{{item}} state=link
      with_items:
        - audio
        - backup
        - dev
        - photos
        - uploads
        - videos

- hosts: dropy
  roles:
    - role: ssh_user
      user: dave
      authorized_hosts:
        - compy
        - happy
        - phone
        - tabby
    - dave
    - jitsi_meet
    - minecraft_server
    - murmur

- hosts: happy
  tasks:
    - name: Blacklist PC Speaker module
      tags: ['pcspeaker', 'pcspkr']
      copy:
        dest: /etc/modprobe.d/nobeep.conf
        content: "blacklist pcspkr"
  roles:
    - syncthing
    - dave
    - development
    - role: ssh_user
      user: dave
      authorized_hosts:
        - servy
        - phone
        - tabby
        - compy
