#!/bin/bash

set -e

export LEDGER_FILE="{{budget_journal_file}}"
if [[ "${1}" == "edit" ]]; then
	dir="$(dirname ${LEDGER_FILE})"
	cd "${dir}"
	file="$(ls -1t | head -n 1)"
	vim -p "${dir}/${file}"
elif [[ "${1}" == "ui" ]]; then
	hledger --auto -V ui -- --watch
elif [[ "${1}" == "add" ]]; then
	hledger $@
elif [[ "${1}" == "quick" ]]; then
	hledger bal --flat -V -O csv | sed 's/assets://' | sed 's/wf://' | sed '/"Account",/d' | sed '/~/d' | sed '/"total"/d' | xclip -selection c
elif [[ "${1}" == "int" || "${1}" == "interest" ]]; then
	if [[ $# -lt 2 ]]; then
		echo "Usage: hl interest [account name]"
		exit 1
	fi
	hledger prices | awk -F' ' '{ print $2 }' | while read line; do
		d=$(date -d "${line}+1day" +%Y-%m-%d)
		echo -n "${d}: "
		hledger bal -N "${2}" -V --end "${d}" | sed 's/^ *//'
	done
else
	hledger --auto $@
fi

