---
- name: "Ensure aws cli is installed"
  package:
    name: awscli
    state: present

- name: "Ensure aws config file is present"
  template:
    src: config
    dest: /home/{{user}}/.aws/config
    mode: 0600

- name: "Ensure aws credentials file is present"
  template:
    src: credentials
    dest: /home/{{user}}/.aws/credentials
    mode: 0600

- name: "Ensure sync cron job is present"
  cron:
    state: "present"
    name: "{{item.prefix}} backup"
    user: "{{user}}"
    special_time: daily
    job: "aws s3 sync {{item.path}} s3://{{s3_sync_bucket_name}}/{{item.prefix}}"
  with_items: "{{s3_sync_items}}"

