---
- name: "Ensure sync cron job is present"
  cron:
    state: "present"
    name: "{{item.prefix}} backup"
    user: "{{user}}"
    hour: "2"
    minute: "0"
    job: "aws s3 sync {{item.path}} s3://{{s3_sync_bucket_name}}/{{item.prefix}} > /dev/null"
  with_items: "{{s3_sync_items}}"

