---
- name: "Ensure aws cli is installed"
  package:
    name: awscli
    state: present

- name: "Ensure aws config file contains default config"
  blockinfile:
    path: /home/{{user}}/.aws/config
    create: yes
    mode: 0600
    insertbefore: BOF
    block: |
      [default]
      region = {{s3_sync_region}}

- name: "Ensure aws credentials file contains default credentials"
  blockinfile:
    path: /home/{{user}}/.aws/credentials
    create: yes
    mode: 0600
    insertbefore: BOF
    block: |
      [default]
      aws_secret_access_key = {{s3_sync_secret_key}}
      aws_access_key_id = {{s3_sync_key}}

- name: "Ensure sync cron job is present"
  cron:
    state: "present"
    name: "{{item.prefix}} backup"
    user: "{{user}}"
    special_time: daily
    job: "aws s3 sync {{item.path}} s3://{{s3_sync_bucket_name}}/{{item.prefix}} > /dev/null"
  with_items: "{{s3_sync_items}}"

