#!/bin/bash

set -e

export LEDGER_FILE=~/docs/personal/finances/budget/main.ledger
if [[ "${1}" == "edit" ]]; then
	dir="$(dirname ${LEDGER_FILE})"
	cd "${dir}"
	file="$(ls -1t | head -n 1)"
	vim -p "${dir}/${file}"
elif [[ "${1}" == "ui" ]]; then
	hledger --auto ui -- --watch
elif [[ "${1}" == "add" ]]; then
	hledger $@
elif [[ "${1}" == "quick" ]]; then
	hl bal --flat -O csv | sed 's/assets://' | sed 's/wf://' | sed '/"Account",/d' | sed '/~/d' | sed '/"total"/d' | xclip -selection c -d ":1"
else
	hledger --auto $@
fi

