#!/bin/bash

set -e

if [[ -z "${SMARTD_MESSAGE}" ]]; then
	SMARTD_MESSAGE="This is a message from the SMART daemon on servy, but I didn't get the text of it."
fi
if [[ -z "${SMARTD_FULLMESSAGE}" ]]; then
	SMARTD_FULLMESSAGE="This is a full message from the SMART daemon on servy, but I didn't get the text of it."
fi
if [[ -z "${SMARTD_SUBJECT}" ]]; then
	SMARTD_SUBJECT="SMART daemon default subject"
fi

# Escape values for JSON
jsonSubject=$(jq -aRs . <<< "${SMARTD_SUBJECT}")
jsonMessage=$(jq -aRs . <<< "${SMARTD_MESSAGE\n\nSMARTD_FULLMESSAGE}")

curl -X POST \
	-H "Content-Type: application/json" \
	-H "Authorization: Basic $(echo -n "{{raid_notify_user}}:{{raid_notify_password}}" | base64)" \
	-d '{ "subject": '"${jsonSubject}"', "body": '"${jsonMessage}"' }' \
	"{{raid_notify_endpoint}}"
