---
- name: Ensure rdiff-backup is installed
  package: name=rdiff-backup state=present

- name: Ensure backup private key is present
  copy:
    src: ssh/{{backup_client_user}}/{{inventory_hostname}}/id_rsa_backup
    dest: "/home/{{backup_client_user}}/.ssh/{{backup_client_keyfile}}"
    mode: 0600
    owner: "{{backup_client_user}}"
    group: "{{backup_client_user}}"

- name: Ensure backup ssh config is present
  blockinfile:
    dest: "/home/{{backup_client_user}}/.ssh/config"
    create: yes
    mode: 0644
    owner: "{{backup_client_user}}"
    group: "{{backup_client_user}}"
    block: |
      host backup
        hostname {{backup_server_host}}.{{hostvars[backup_server_host].domain}}
        user {{backup_server_user}}
        identityfile /home/{{backup_client_user}}/.ssh/{{backup_client_keyfile}}

- name: Ensure local bin directory is present in user home
  file:
    state: directory
    dest: "/home/{{backup_client_user}}/.local/bin/"
    mode: 0755
    owner: "{{backup_client_user}}"
    group: "{{backup_client_user}}"

- name: Ensure backup script is present
  template:
    src: backup.sh
    dest: "/home/{{backup_client_user}}/.local/bin/backup.sh"
    mode: 0744
    owner: "{{backup_client_user}}"
    group: "{{backup_client_user}}"
    
- name: Ensure cron task is present
  cron:
    name: "Backup documents"
    state: present
    user: "{{backup_client_user}}"
    special_time: daily
    job: "~/.local/bin/backup.sh"

