---
- name: Ensure borg is installed
  package: name={{borg_pkg}} state=latest

- name: Ensure borgmatic is installed
  package: name=borgmatic state=latest

- name: Ensure llfuse is installed (for mounting backups)
  package: name={{llfuse_pkg}} state=latest

- name: Ensure backup private key is present
  copy:
    src: ssh/{{item.user}}/{{inventory_hostname}}/id_rsa_backup
    dest: "{% if item.user == 'root' %}/root{% else %}/home/{{item.user}}{% endif %}/.ssh/id_rsa_backup"
    mode: 0600
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure borgmatic config dir is present
  file:
    state: directory
    name: "{% if item.user == 'root' %}/etc/borgmatic{% else %}/home/{{item.user}}/.config{% endif %}/borgmatic.d"
    mode: 0755
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure backup config is present
  template:
    src: borgmatic_config.yml.j2
    dest: "{% if item.user == 'root' %}/etc/borgmatic{% else %}/home/{{item.user}}/.config{% endif %}/borgmatic.d/{{item.name}}.yml"
    mode: 0644
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure cron task is present
  cron:
    name: "Backup: {{item.name}}"
    state: present
    user: "{{item.user}}"
    special_time: daily
    job: "borgmatic --syslog-verbosity 1"
  loop: "{{borgmatic_configs}}"

