---
- name: Ensure borg is installed
  package: name={{borg_pkg}} state=latest

- name: Ensure borgmatic is installed
  package: name=borgmatic state=latest
  when: ansible_os_family != "Debian"

# Ubuntu LTS does not have borgmatic, so we have to install via pip
- name: Ensure pip is installed
  package: name={{pip_pkg}} state=latest
  when: ansible_os_family == "Debian"

- name: Ensure borgmatic is installed via pip
  pip:
    name: "borgmatic"
    state: latest
    executable: pip3
  when: ansible_os_family == "Debian"

- name: Ensure llfuse is installed (for mounting backups)
  package: name={{llfuse_pkg}} state=latest

- name: Ensure backup private key is present
  copy:
    src: "ssh/{{item.user}}/{{inventory_hostname}}/{{item.ssh_key | default('id_rsa_backup')}}"
    dest: "{% if item.user == 'root' %}/root{% else %}/home/{{item.user}}{% endif %}/.ssh/{{item.ssh_key | default('id_rsa_backup')}}"
    mode: 0600
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure borgmatic config dir is present
  file:
    state: directory
    name: "{% if item.user == 'root' %}/etc{% else %}/home/{{item.user}}/.config{% endif %}/borgmatic.d"
    mode: 0755
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure backup config is present
  template:
    src: borgmatic_config.yml.j2
    dest: "{% if item.user == 'root' %}/etc{% else %}/home/{{item.user}}/.config{% endif %}/borgmatic.d/{{item.name}}.yml"
    mode: 0644
    owner: "{{item.user}}"
    group: "{{item.user}}"
  loop: "{{borgmatic_configs}}"

- name: Ensure cron task is present in user crontab
  cron:
    name: "Backup: {{item.name}}"
    state: present
    user: "{{item.user}}"
    hour: "3"
    minute: "0"
    job: "PATH=$PATH:/usr/bin:/usr/local/bin:$HOME/.local/bin borgmatic --syslog-verbosity 1"
  loop: "{{borgmatic_configs}}"
  when: "{{item.user != 'root'}}"

- name: Ensure daily cron (or anacron) script is in /etc/cron.daily
  copy:
    src: daily.sh
    dest: "/etc/cron.daily/borgmatic"
    mode: 0755
  when: "{{item.user == 'root'}}"
  loop: "{{borgmatic_configs}}"
