---
storage_device: /dev/md/storage
storage_root: /mnt/storage
docker_root: "{{storage_root}}/docker"

# RAID config
raid_notify_user: "{{vault_raid_notify_user}}"
raid_notify_password: "{{vault_raid_notify_password}}"
raid_notify_endpoint: "{{vault_raid_notify_endpoint}}"

# DNS config
hosts:
  - { ip: 10.1.1.1, host: "{{vault_dyndns_domain}}.duckdns.org" }
  - { ip: 10.1.1.1, host: servy }
  - { ip: 10.1.42.1, host: compy }
  - { ip: 10.1.42.2, host: happy }
  - { ip: 10.1.143.2, host: asuzw }
  - { ip: 10.1.143.1, host: asuz }
  - { ip: 10.1.0.1, host: rowdy}
  - { ip: 10.2.0.1, host: rowdyjr}
domain: "{{vault_domain}}"
public_domain: "{{vault_public_domain}}"

# OpenVPN Server config
openvpn_pki_pass: "{{vault_openvpn_pki_pass}}"
openvpn_clients:
  - happy
  - tabby
  - dcell
  - scell
openvpn_key_dir: "{{storage_root}}/backup/keys"

# OpenVPN Client config
openvpn_provider: "{{vault_openvpn_provider}}"
openvpn_config: "{{vault_openvpn_config}}"
openvpn_username: "{{vault_openvpn_username}}"
openvpn_password: "{{vault_openvpn_password}}"
torrent_dir: "{{docker_root}}/torrent"
torrent_blocklist_enabled: "true"
torrent_blocklist_url: "{{vault_torrent_blocklist_url}}"
torrent_speed_limit_up: "10000"
torrent_speed_limit_up_enabled: "true"
torrent_speed_limit_down: "20000"
torrent_speed_limit_down_enabled: "true"

# Plex config
plex_config_dir: "{{docker_root}}/plex/config"
plex_upload_dir: "{{docker_root}}/plex/upload"
plex_media_dir: "{{storage_root}}"

# Smokeping config
smokeping_dir: "{{docker_root}}/smokeping"
smokeping_port: "8090"

# DynDNS config
dyndns_domain: "{{vault_dyndns_domain}}"
dyndns_token: "{{vault_dyndns_token}}"

# Minecraft config
minecraft_dir: "{{docker_root}}/minecraft"
minecraft_server_env:
  OPS: 'thoughtcriminal'
  MEMORY: '1536M' # 1.5G
  USE_AIKAR_FLAGS: 'true'
  CONSOLE: 'false'
  GUI: 'false'
  TZ: 'America/Chicago'
  OVERRIDE_SERVER_PROPERTIES: 'true'
  ONLINE_MODE: 'true'
  #
  # Vanilla creative
  #
  # TYPE: vanilla
  # MOTD: 'Family creative mode server'
  # VERSION: 'LATEST'
  # LEVEL: 'world-boyscreative'
  # MODE: 'creative'
  # DIFFICULTY: 'easy'
  # SPAWN_PROTECTION: '16'
  # VIEW_DISTANCE: '10'
  # ONLINE_MODE: 'true'
  #
  # Drehmal
  #
  TYPE: vanilla
  MOTD: 'Drehmal: Primordial'
  VERSION: '1.16.4'
  LEVEL: 'world-drehmal'
  MODE: 'survival'
  DIFFICULTY: 'easy'
  SPAWN_PROTECTION: '0'
  VIEW_DISTANCE: '20'
  #
  # Island of Sodor
  #
  #TYPE: 'FORGE'
  #VERSION: '1.7.10'
  #MOTD: 'A Traincraft server'
  #LEVEL: 'world-sodor'
  #MODE: 'creative'
  #DIFFICULTY: 'normal'
  #
  # Super Hostile
  #
  # TYPE: vanilla
  # MOTD: 'Super Hostile: Infernal Sky II'
  # VERSION: '1.2.5'
  # LEVEL: 'world-superhostile'
  # MODE: 'survival'
  # DIFFICULTY: 'normal'
  # SPAWN_PROTECTION: '16'
  # VIEW_DISTANCE: '20'
 
# NGINX config
http_static_config_file: "{{docker_root}}/http/static.conf"
http_static_dir: "{{docker_root}}/http/static"

backup_server_root_dir: "{{storage_root}}/backup/borg"
backup_client_configs:
  - user: root
    host: compy
  - user: root
    host: asuz

borgmatic_configs: [] # TODO Add borgmatic configs

# AWS CLI
aws_key: "AKIAZ4U4D4642YOPPJNZ"
aws_secret_key: "{{vault_aws_secret_key}}"
aws_region: "us-east-1"

# hledger config
hledger_dir: "{{storage_root}}/sync/budget"

# nfs config
nfs_mounts:
  - dir: "{{storage_root}}/videos"
    name: videos
  - dir: "{{storage_root}}/audio/music"
    name: music
  - dir: "{{storage_root}}/photos"
    name: photos

digital_ocean_token: "{{vault_digital_ocean_token}}"

# Traefik config
traefik_do_token: "{{vault_traefik_do_token}}"
traefik_config_dir: "{{docker_root}}/traefik"

dns_allowlist: |
  # Domains added below will be ignored, For example:
  # your-domain-name.com
  adjust.com
  ads.mopub.com
  api.mixpanel.com
  app-measurement.com
  applovin.com
  applvn.com
  crashlytics.com
  decide.mixpanel.com
  googleadservices.com
  googlesyndication.com
  invenio.sgn.com
  jamcity.com
  live.chartboost.com
  moatads.com
  sessions.bugsnag.com
  supersonicads.com
  swrve.com
  unity3d.com
  mobileandroidapi.punchh.com
  # ssacdn.com
  # doubleclick.net

