---
storage_device: /dev/md/storage
storage_root: /mnt/storage
docker_root: "{{storage_root}}/docker"

# RAID config
raid_notify_user: "{{vault_raid_notify_user}}"
raid_notify_password: "{{vault_raid_notify_password}}"
raid_notify_endpoint: "{{vault_raid_notify_endpoint}}"

# nfs config
nfs_mounts:
  - dir: "{{storage_root}}/videos"
    name: videos
  - dir: "{{storage_root}}/audio/music"
    name: music
  - dir: "{{storage_root}}/photos"
    name: photos

# DNS config
hosts:
  - { ip: 10.1.1.1, host: "{{vault_dyndns_domain}}.duckdns.org" }
  - { ip: 10.1.1.1, host: servy }
  - { ip: 10.1.42.1, host: compy }
  - { ip: 10.1.42.2, host: happy }
  - { ip: 10.1.143.2, host: asuzw }
  - { ip: 10.1.143.1, host: asuz }
  - { ip: 10.1.0.1, host: rowdy}
  - { ip: 10.2.0.1, host: rowdyjr}
domain: "{{vault_domain}}"
public_domain: "{{vault_public_domain}}"

dns_allowlist: |
  # Domains added below will be ignored, For example:
  # your-domain-name.com
  adjust.com
  ads.mopub.com
  api.mixpanel.com
  app-measurement.com
  applovin.com
  applvn.com
  crashlytics.com
  decide.mixpanel.com
  googleadservices.com
  googlesyndication.com
  invenio.sgn.com
  jamcity.com
  live.chartboost.com
  moatads.com
  sessions.bugsnag.com
  supersonicads.com
  swrve.com
  unity3d.com
  mobileandroidapi.punchh.com

# DynDNS config
dyndns_domain: "{{vault_dyndns_domain}}"
dyndns_token: "{{vault_dyndns_token}}"

# Plex config
plex_config_dir: "/var/lib/plexmediaserver" # On SSD, not RAID
plex_upload_dir: "{{docker_root}}/plex/upload"
plex_media_dir: "{{storage_root}}"

hledger_dir: "{{storage_root}}/docs/budget"

# Smokeping config
smokeping_dir: "/opt/smokeping"

# NGINX config
http_static_config_file: "/opt/http/static.conf"
http_static_dir: "/opt/http/static"

# Minecraft config
minecraft_dir: "/opt/minecraft"
minecraft_server_env:
  OPS: 'thoughtcriminal'
  MEMORY: '4G' # 1.5G
  USE_AIKAR_FLAGS: 'true'
  CONSOLE: 'false'
  GUI: 'false'
  TZ: 'America/Chicago'
  OVERRIDE_SERVER_PROPERTIES: 'true'
  ONLINE_MODE: 'true'
  #
  # Vanilla creative
  #
  TYPE: vanilla
  MOTD: 'Family creative mode server'
  VERSION: 'LATEST'
  LEVEL: 'world-boyscreative'
  MODE: 'creative'
  DIFFICULTY: 'easy'
  SPAWN_PROTECTION: '16'
  VIEW_DISTANCE: '10'
  #
  # Drehmal
  #
  #TYPE: vanilla
  #MOTD: 'Drehmal: Primordial'
  #VERSION: '1.16.4'
  #LEVEL: 'world-drehmal'
  #MODE: 'survival'
  #DIFFICULTY: 'easy'
  #SPAWN_PROTECTION: '0'
  #VIEW_DISTANCE: '20'
  #
  # Island of Sodor
  #
  #TYPE: 'FORGE'
  #VERSION: '1.7.10'
  #MOTD: 'A Traincraft server'
  #LEVEL: 'world-sodor'
  #MODE: 'creative'
  #DIFFICULTY: 'normal'
  #
  # Super Hostile
  #
  # TYPE: vanilla
  # MOTD: 'Super Hostile: Infernal Sky II'
  # VERSION: '1.2.5'
  # LEVEL: 'world-superhostile'
  # MODE: 'survival'
  # DIFFICULTY: 'normal'
  # SPAWN_PROTECTION: '16'
  # VIEW_DISTANCE: '20'

# Traefik config
traefik_do_token: "{{vault_traefik_do_token}}"
traefik_config_dir: "{{docker_root}}/traefik"

# Backup server config
backup_server_root_dir: "{{storage_root}}/backup/borg"
backup_client_configs:
  - user: root
    host: compy
  - user: root
    host: asuz

borgmatic_configs:
  - name: misc
    user: root
    passphrase: "{{vault_borg_passphrase}}"
    healthcheck_uuid: "{{vault_borg_healthcheck_uuid_misc}}"
    source_dirs:
      - "/mnt/storage/backup/dev"
      - "/mnt/storage/backup/games"
      - "/mnt/storage/backup/keys"
      - "/mnt/storage/backup/software"
      - "/mnt/storage/backup/trivia"
    repositories:
      - "{{vault_borg_repo}}"
  - name: minecraft
    user: root
    passphrase: "{{vault_borg_passphrase}}"
    healthcheck_uuid: "{{vault_borg_healthcheck_uuid_minecraft}}"
    source_dirs:
      - "{{minecraft_dir}}"
    repositories:
      - "{{vault_borg_repo}}"
    before_backup:
      - "docker exec -i minecraft rcon-cli save-off || true" # or minecraft is not running
      - "docker exec -i minecraft rcon-cli save-all || true"
    after_backup:
      - "docker exec -i minecraft rcon-cli save-on || true"
  - name: plex
    user: root
    passphrase: "{{vault_borg_passphrase}}"
    healthcheck_uuid: "{{vault_borg_healthcheck_uuid_plex}}"
    source_dirs:
      - "{{plex_config_dir}}"
    repositories:
      - "{{vault_borg_repo}}"
    before_backup:
      - "docker stop plex"
    after_backup:
      - "docker start plex"
  - name: smokeping
    user: root
    passphrase: "{{vault_borg_passphrase}}"
    healthcheck_uuid: "{{vault_borg_healthcheck_uuid_smokeping}}"
    source_dirs:
      - "{{smokeping_dir}}/data"
    repositories:
      - "{{vault_borg_repo}}"
    before_backup:
      - "docker stop smokeping"
    after_backup:
      - "docker start smokeping"

# OpenVPN Server config
openvpn_pki_pass: "{{vault_openvpn_pki_pass}}"
openvpn_clients:
  - happy
  - tabby
  - dcell
  - scell
openvpn_key_dir: "{{storage_root}}/backup/keys"

# OpenVPN Client config
openvpn_provider: "{{vault_openvpn_provider}}"
openvpn_config: "{{vault_openvpn_config}}"
openvpn_username: "{{vault_openvpn_username}}"
openvpn_password: "{{vault_openvpn_password}}"
torrent_dir: "{{docker_root}}/torrent"
torrent_blocklist_enabled: "true"
torrent_blocklist_url: "{{vault_torrent_blocklist_url}}"
torrent_speed_limit_up: "10000"
torrent_speed_limit_up_enabled: "true"
torrent_speed_limit_down: "20000"
torrent_speed_limit_down_enabled: "true"

# AWS CLI
aws_key: "AKIAZ4U4D4642YOPPJNZ"
aws_secret_key: "{{vault_aws_secret_key}}"
aws_region: "us-east-1"

digital_ocean_token: "{{vault_digital_ocean_token}}"

couchdb_config_path: "{{docker_root}}/couchdb/"
couchdb_password: "{{vault_couchdb_password}}"

