---
storage_uuid: "4ba8b760-634e-4915-9d61-bfcc27f19848"
storage_root: /mnt/storage
docker_root: "{{storage_root}}/docker"

# DNS config
hosts:
  - { ip: 192.168.2.150, host: servy }
  - { ip: 192.168.2.142, host: compy }
  - { ip: 192.168.2.143, host: asuzw }
  - { ip: 192.168.2.144, host: asuz }
  - { ip: 192.168.2.1, host: rowdy}
  - { ip: 192.168.1.1, host: rowdyjr}
domain: "{{vault_domain}}"
public_domain: "{{vault_public_domain}}"

# OpenVPN Server config
openvpn_pki_pass: "{{vault_openvpn_pki_pass}}"
openvpn_clients:
  - tabby
  - dcell
  - scell
openvpn_key_dir: "{{storage_root}}/backup/keys"

# OpenVPN Client config
openvpn_provider: "{{vault_openvpn_provider}}"
openvpn_config: "{{vault_openvpn_config}}"
openvpn_username: "{{vault_openvpn_username}}"
openvpn_password: "{{vault_openvpn_password}}"
torrent_dir: "{{docker_root}}/torrent"
torrent_blocklist_enabled: "true"
torrent_blocklist_url: "{{vault_torrent_blocklist_url}}"
torrent_speed_limit_up: "10000"
torrent_speed_limit_up_enabled: "true"
torrent_speed_limit_down: "20000"
torrent_speed_limit_down_enabled: "true"

# Plex config
plex_config_dir: "{{docker_root}}/plex/config"
plex_upload_dir: "{{docker_root}}/plex/upload"
plex_media_dir: "{{storage_root}}"

# Smokeping config
smokeping_dir: "{{docker_root}}/smokeping"
smokeping_port: "8090"

# DynDNS config
dyndns_domain: "{{vault_dyndns_domain}}"
dyndns_token: "{{vault_dyndns_token}}"

# Minecraft config
minecraft_dir: "{{docker_root}}/minecraft"

# NGINX config
http_static_config_file: "{{docker_root}}/nginx/static.conf"
http_static_dir: "{{docker_root}}/http/static"

backup_server_root_dir: "{{storage_root}}/backup"
backup_server_configs:
  - dir: suz
    public_key: "{{ssh_backup_keys.suz.asuz}}"

