---
storage_uuid: "4ba8b760-634e-4915-9d61-bfcc27f19848"

# DNS config
hosts:
  - { ip: 192.168.2.150, host: servy }
  - { ip: 192.168.2.142, host: compy }
  - { ip: 192.168.2.1, host: rowdy}
  - { ip: 192.168.1.1, host: rowdyjr}
domain: "{{vault_domain}}"
public_domain: "{{vault_public_domain}}"

# OpenVPN Server config
openvpn_pki_pass: "{{vault_openvpn_pki_pass}}"
openvpn_clients:
  - tabby
  - dcell
  - scell
openvpn_key_dir: "/mnt/storage/backup/keys"

# OpenVPN Client config
openvpn_provider: "{{vault_openvpn_provider}}"
openvpn_config: "{{vault_openvpn_config}}"
openvpn_username: "{{vault_openvpn_username}}"
openvpn_password: "{{vault_openvpn_password}}"
smokeping_dir: "/mnt/storage/docker/smokeping"
smokeping_port: "8090"
torrent_dir: "/mnt/storage/docker/torrent"
torrent_blocklist_enabled: "true"
torrent_blocklist_url: "{{vault_torrent_blocklist_url}}"
torrent_speed_limit_up: "10000"
torrent_speed_limit_up_enabled: "true"
torrent_speed_limit_down: "20000"
torrent_speed_limit_down_enabled: "true"

# Plex config
plex_config_dir: "/mnt/storage/docker/plex/config"
plex_upload_dir: "/mnt/storage/docker/plex/upload"
plex_media_dir: "/mnt/storage"

