---
storage_uuid: "4ba8b760-634e-4915-9d61-bfcc27f19848"
storage_root: /mnt/storage
docker_root: "{{storage_root}}/docker"

# DNS config
hosts:
  - { ip: 10.1.1.1, host: "{{vault_dyndns_domain}}.duckdns.org" }
  - { ip: 10.1.1.1, host: servy }
  - { ip: 10.1.42.1, host: compy }
  - { ip: 10.1.42.2, host: happy }
  - { ip: 10.1.143.2, host: asuzw }
  - { ip: 10.1.143.1, host: asuz }
  - { ip: 10.1.0.1, host: rowdy}
  - { ip: 10.2.0.1, host: rowdyjr}
domain: "{{vault_domain}}"
public_domain: "{{vault_public_domain}}"

# OpenVPN Server config
openvpn_pki_pass: "{{vault_openvpn_pki_pass}}"
openvpn_clients:
  - happy
  - tabby
  - dcell
  - scell
openvpn_key_dir: "{{storage_root}}/backup/keys"

# OpenVPN Client config
openvpn_provider: "{{vault_openvpn_provider}}"
openvpn_config: "{{vault_openvpn_config}}"
openvpn_username: "{{vault_openvpn_username}}"
openvpn_password: "{{vault_openvpn_password}}"
torrent_dir: "{{docker_root}}/torrent"
torrent_blocklist_enabled: "true"
torrent_blocklist_url: "{{vault_torrent_blocklist_url}}"
torrent_speed_limit_up: "10000"
torrent_speed_limit_up_enabled: "true"
torrent_speed_limit_down: "20000"
torrent_speed_limit_down_enabled: "true"

# Plex config
plex_config_dir: "{{docker_root}}/plex/config"
plex_upload_dir: "{{docker_root}}/plex/upload"
plex_media_dir: "{{storage_root}}"

# Smokeping config
smokeping_dir: "{{docker_root}}/smokeping"
smokeping_port: "8090"

# DynDNS config
dyndns_domain: "{{vault_dyndns_domain}}"
dyndns_token: "{{vault_dyndns_token}}"

# Minecraft config
minecraft_dir: "{{docker_root}}/minecraft"
minecraft_server_env:
  MODE: creative

# NGINX config
http_static_config_file: "{{docker_root}}/nginx/static.conf"
http_static_dir: "{{docker_root}}/http/static"

backup_server_root_dir: "{{storage_root}}/backup/borg"
backup_client_configs:
  - user: root
    host: compy
  - user: root
    host: asuz

borgmatic_configs:
  - name: minecraft
    user: dave
    passphrase: "{{vault_borg_minecraft_passphrase}}"
    ssh_key: "id_rsa_borgbase"
    source_dirs:
      - /mnt/storage/docker/minecraft
    repositories:
      - "{{vault_borg_minecraft_repo}}"
    before_backup:
      - "rcon save-off"
      - "rcon save-all"
    after_backup:
      - "rcon save-on"

# AWS CLI
aws_key: "AKIAZ4U4D464WU5YA6GU"
aws_secret_key: "{{vault_aws_secret_key}}"
aws_region: "us-east-1"

# Wasabi CLI
wasabi_key: "ZGY6IWQSZRDT8ZDRNAEI"
wasabi_secret_key: "{{vault_wasabi_secret_key}}"

# hledger config
hledger_dir: "/mnt/storage/sync/budget"

# nfs config
nfs_mounts:
  - dir: /mnt/storage/videos
    name: videos
  - dir: /mnt/storage/audio/music
    name: music
  - dir: /mnt/storage/photos
    name: photos

digital_ocean_token: "{{vault_digital_ocean_token}}"

couchdb_config_path: "{{docker_root}}/couchdb/"
couchdb_password: "{{vault_couchdb_password}}"

