---
- name: Ensure Digikam is installed
  package: name=digikam state=latest

- name: Ensure exiftool is installed
  package: name=perl-image-exiftool state=latest

- name: Clone photo-management repository
  git: 
    repo: "https://github.com/{{github_user}}/photo-management.git"
    dest: "/opt/photo-management"
    force: true

- name: Ensure config file is present
  copy: 
    content: "{{ lookup('file', 'host_vars/{{ansible_hostname}}/files/photo-mgmt.cfg')}}"
    dest: /opt/photo-management/config.cfg

- name: Ensure secrets file is present
  copy: 
    content: "{{ lookup('file', 'host_vars/{{ansible_hostname}}/files/photo-mgmt-secrets.cfg')}}"
    dest: /opt/photo-management/secrets.cfg
