---
- name: Ensure mosh is installed
  package: name=mosh state=present

- name: Ensure tmux is installed
  package: name=tmux state=present

- name: Ensure git is installed
  package: name=git state=present

- name: Ensure zsh is installed
  package: name=zsh state=present

- name: Ensure zip is installed
  package: name=zip state=present

- name: Ensure unzip is installed
  package: name=unzip state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure tree is installed
  package: name=tree state=present

- name: Ensure pv is installed
  package: name=pv state=present

# TODO This is a pre-requisite for installing tomb on arch, but tomb still can't be
# installed because it's only in the AUR.
#- name: Ensure tomb gpg key is imported
  ## Pinned comment at https://aur.archlinux.org/packages/tomb/ as of this
  ## writing. In the future, this could be expanded into a GPG role that include
  ## configuring the keyserver globally.
  #command: gpg --keyserver pool.sks-keyservers.net --recv-keys 6113D89CA825C5CEDD02C87273B35DA54ACB7D10
  #when: ansible_os_family == "Archlinux"

- name: Ensure tomb in installed
  package: name=tomb state=present

- name: Ensure bat is installed
  package: name=bat state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure fd is installed
  package: name=fd state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure dmenu is installed
  package: name=dmenu state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure man is installed
  package: name=man-db state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure man pages are installed
  package: name=man-pages state=present
  when: ansible_os_family == "Archlinux"

- name: Ensure ag is installed
  package: name={{ag_pkg}} state=present

- name: Ensure urxvt is installed on GUI machines
  package: name=rxvt-unicode state=present
  when: "'headless' not in group_names"

