---
- name: "Ensure hledger-web container is started"
  docker_container:
    name: hledger
    image: dastapov/hledger
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{hledger_dir}}:/data"
    ports:
      - "5000:5000"
    env:
      HLEDGER_JOURNAL_FILE: "/data/main.ledger"
      HLEDGER_BASE_URL: "http://budget.{{ansible_hostname}}.{{domain}}"
      VIRTUAL_HOST: "budget.{{ansible_hostname}}.{{domain}}"
      VIRTUAL_PORT: "5000"
    labels:
      "traefik.http.routers.hledger.rule": "Host(`budget.{{ansible_hostname}}.{{domain}}`)"

