---
- name: "Ensure hledger-web container is started"
  docker_container:
    name: hledger
    image: dastapov/hledger
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{hledger_dir}}:/data"
    ports:
      - "5000:5000"
    command: "hledger-web --serve --host='0.0.0.0' --file='/data/main.ledger' --base-url=https://budget.{{ansible_hostname}}.{{domain}} --cors='*'"
    env:
      VIRTUAL_HOST: "budget.{{ansible_hostname}}.{{domain}}"
      VIRTUAL_PORT: "5000"
    labels:
      "traefik.http.routers.hledger.rule": "Host(`budget.{{ansible_hostname}}.{{domain}}`)"
      "traefik.http.routers.hledger.middlewares": "tls-redirect"
      "traefik.http.routers.hledger-secure.rule": "Host(`budget.{{ansible_hostname}}.{{domain}}`)"
      "traefik.http.routers.hledger-secure.tls": "true"
      "traefik.http.routers.hledger-secure.tls.certresolver": "do-resolver"

