---
- name: Ensure Digikam is installed
  package: name=digikam state=latest

- name: Ensure exiftool is installed
  package: name=perl-image-exiftool state=latest

- name: Clone photo-management repository
  git: 
    repo: "https://github.com/{{github_user}}/photo-management.git"
    dest: "{{install_dir}}"
    force: true

- name: Ensure config file is present
  copy: 
    content: "{{ lookup('file', 'host_vars/{{ansible_hostname}}/files/photo-mgmt.cfg')}}"
    dest: "{{install_dir}}/config.cfg"

- name: Ensure secrets file is present
  copy: 
    content: "{{ lookup('file', 'host_vars/{{ansible_hostname}}/files/photo-mgmt-secrets.cfg')}}"
    dest: "{{install_dir}}/secrets.cfg"

- name: Ensure /opt/bin exists
  file: name=/opt/bin state=directory

- name: Ensure run script is on PATH
  file:
    src: "{{install_dir}}/run.sh"
    dest: /opt/bin/photoimport
    state: link

- name: Ensure backup script is on PATH
  file:
    name: /opt/bin/photobackup
    state: link
    src: "{{install_dir}}/run-backup.sh"

- name: Ensure borg backup script is on PATH
  template:
    src: borg-backup-photos.sh
    dest: /home/{{user}}/.local/bin/backup-photos.sh
    owner: "{{user}}"
    group: "{{user}}"
    mode: "755"

- name: Ensure borg backup key is installed
  copy:
    content: "{{ lookup('file', 'host_vars/{{ansible_hostname}}/files/borg-key-photos.vault')}}"
    dest: /home/{{user}}/.config/borg/keys/servy__mnt_storage_backup_borg_photos
    owner: "{{user}}"
    group: "{{user}}"
    mode: "0600"

- name: "Ensure borg backup is scheduled"
  cron:
    state: "present"
    name: "borg photo backup"
    user: "{{user}}"
    special_time: daily
    job: /home/{{user}}/.local/bin/backup-photos.sh

