---
- name: Add hosts
  lineinfile:
    path: /etc/hosts
    regexp: ".*\\s{{item.host}}$"
    line: "{{item.ip}}	{{item.host}}"
  with_items: "{{hosts}}"

- name: Disable systemd-resolved stub listener
  lineinfile:
    path: "/etc/systemd/resolved.conf"
    line: "DNSStubListener=no"
    regexp: "DNSStubListener="

- name: Manage resolv.conf file
  copy:
    backup: yes
    dest: /etc/resolv.conf
    content: |
      # Managed by Ansible
      nameserver 127.0.0.1
      search {{domain}}
    mode: 644

- name: Ensure DNS traffic allowed through firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: 'domain' # 53

- name: Clone hosts repository
  git: 
    repo: "https://github.com/StevenBlack/hosts.git"
    dest: "{{hosts_repo_dir}}"
    update: no

- name: Ensure blacklist update task is scheduled
  template:
    src: update-dns-blacklist.sh
    dest: /etc/cron.weekly
    mode: 0755

- name: Ensure blacklist update has been run once
  command:
    cmd: "/etc/cron.weekly/update-dns-blacklist.sh"
    # 'creates' could also use whitelist/blacklist or touch a file in the update script
    creates: "{{hosts_repo_dir}}/myhosts"

- name: Ensure docker container is started
  tags: ['vpn-dnsfix']
  docker_container:
    name: dns
    image: andyshinn/dnsmasq
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
      - "{{hosts_repo_dir}}/hosts:/etc/hosts-blacklist:ro"
    ports:
      - 53:53/tcp
      - 53:53/udp
    capabilities:
      - NET_ADMIN
    command: >
      --address /.{{ansible_hostname}}.{{domain}}/{{ansible_default_ipv4.address}}
      --domain={{domain}}
      --addn-hosts=/etc/hosts-blacklist
      --no-resolv
      --no-negcache
      --server 9.9.9.9
      --server 149.112.112.112
      --expand-hosts
      --log-facility=-
      --dns-forward-max 1000
      --domain-needed
      --bogus-priv
  register: "docker_dns_container_status"

