---
borgmatic_configs:
  - name: home
    user: root
    passphrase: "{{vault_borg_passphrase}}"
    healthcheck_uuid: "{{vault_borg_healthcheck_uuid}}"
    source_dirs:
      - /home/suz
    repositories:
      - "{{vault_borg_domain}}:/mnt/storage/backup/borg/asuz/root"
      - "gw6a7f8p@gw6a7f8p.repo.borgbase.com:repo"
    exclude_patterns:
      - "/home/suz/Desktop/Recent Photos"
      - "/home/suz/Pictures"

