traefik_tls_resolver: do-resolver
traefik_do_token: ''
traefik_labels:
  "traefik.http.routers.traefik.rule": "Host(`traefik.{{ansible_hostname}}.{{domain}}`)"
  "traefik.http.services.traefik.loadbalancer.server.port": "8080"
  "traefik.http.routers.traefik.tls": "true"
  "traefik.http.routers.traefik.tls.certresolver": "{{traefik_tls_resolver}}"
