---
- name: Ensure HTTP traffic allowed through firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: 'http'

- name: Ensure HTTPS traffic allowed through firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: 'https'

- name: Ensure traefik config dir is present
  file:
    name: "{{traefik_config_dir}}"
    state: directory
    mode: 0755

- name: Ensure traefik config file is present
  template:
    src: traefik.toml
    dest: "{{traefik_config_dir}}/traefik.toml"
  notify: restart_traefik

- name: Ensure acme.json is present
  file:
    path: "{{traefik_config_dir}}/acme.json"
    mode: 0600

- name: Ensure traefik container is started
  tags: ['traefik']
  docker_container:
    name: traefik
    image: traefik
    state: started
    restart_policy: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{traefik_config_dir}}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "{{traefik_config_dir}}/acme.json:/acme.json:rw"
    env:
      "DO_AUTH_TOKEN": "{{traefik_do_token}}"
    labels: "{{traefik_labels}}"
