---
- name: Ensure static config file exists
  template:
    src: static.conf
    dest: "{{http_static_config_file}}"

- name: Ensure nginx container is started
  docker_container:
    name: nginx
    image: nginx
    pull: true
    state: started
    restart_policy: always
    ports:
      - 9080:80/tcp
    volumes:
      - "{{http_static_dir}}:/usr/share/nginx/html:ro"
      - "{{http_static_config_file}}:/etc/nginx/conf.d/static.conf:ro"
    labels:
      "traefik.http.routers.nginx.rule": "Host(`static.{{ansible_hostname}}.{{domain}}`)"

- name: Ensure HTTP traffic allowed through firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: 'http'

- name: Ensure traefik container is started
  tags: ['traefik']
  docker_container:
    name: traefik
    image: traefik
    state: started
    restart_policy: unless-stopped
    ports:
      - 80:80/tcp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: "--api.insecure=true --providers.docker"
    labels:
      "traefik.http.routers.traefik.rule": "Host(`traefik.{{ansible_hostname}}.{{domain}}`)"
      "traefik.http.services.traefik.loadbalancer.server.port": "8080"

