---
- name: Ensure docker is installed
  apt: name=docker.io state=installed

- name: Add a docker group
  group: name=docker

- name: Add non-root user {{user}} to docker group
  user: name={{user}} groups=docker append=true
