---
- name: Ensure docker is installed
  package: name={{docker_pkg}} state=present

- name: Ensure docker-compose is installed
  package: name=docker-compose state=present

- name: Add a docker group
  group: name=docker

- name: Add non-root user {{user}} to docker group
  user: name={{user}} groups=docker append=true

- name: Ensure pip is installed
  package: name={{pip_pkg}} state=latest

- name: install certain python modules for docker
  pip:
    name: "{{item}}"
    state: latest
    executable: pip3
  loop: ['docker', 'docker-compose']

- name: Add docker-clean script
  copy:
    src: docker-cleanup.sh
    dest: /home/{{user}}/.local/bin/docker-cleanup.sh
    mode: 0755
    owner: "{{user}}"
    group: "{{user}}"
