---
- name: Ensure docker is installed
  apt: name=docker.io state=present

- name: Add a docker group
  group: name=docker

- name: Add non-root user {{user}} to docker group
  user: name={{user}} groups=docker append=true

- name: Ensure pip is installed
  apt: name=python-pip state=latest

- name: install certain python modules for docker
  pip:
    name: docker
    state: latest

