---
- name: Remove old packages
  apt: name={{item}} state=absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Ensure apt can use https
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Detect Ubuntu version
  command: lsb_release
  register: release_name

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{release_name.stdout}} stable
    state: present
    filename: docker

- name: Ensure docker is installed
  apt: name={{item}} state=present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

