---
- name: Ensure smartmontools is installed
  apt: name=smartmontools state=present

- name: Add smartd.conf
  copy: src=smartd.conf dest=/etc/smartd.conf

- name: Add smartmontools run script for mutt
  template: src=10notify dest=/etc/smartmontools/run.d/10notify mode=755

- name: Ensure smartmontools is started
  service: name=smartmontools enabled=yes state=started

