---
- import_tasks: mdadm.yml
- import_tasks: smart.yml
- name: Ensure storage raid is mounted
  mount:
    path: "{{storage_root}}"
    src: "{{storage_device}}"
    fstype: ext4
    opts: defaults 
    state: mounted

