---
- name: Update all apt packages to the latest version
  apt: upgrade=dist update_cache=yes
  when: ansible_os_family == "Debian"

- include_tasks: utils.yml
- include_tasks: user.yml
- include_tasks: security.yml

