---
- name: Update all apt packages to the latest version
  apt: upgrade=dist update_cache=yes
  when: ansible_os_family == "Debian"

- name: Ensure local bin directory exists
  file:
    dest: /home/{{admin_user}}/.local/bin
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"

- name: Add Arch upgrade script
  copy:
    src: upgrade.sh
    dest: /home/{{admin_user}}/.local/bin/upgrade.sh
    mode: 0755
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
  when: ansible_os_family == "Archlinux"

- name: Ensure reboot-if-needed script is present
  copy:
    src: "reboot-if-needed.sh"
    dest: "/root/reboot-if-needed.sh"
    mode: "0755"
  when: "'headless' in group_names and ansible_pkg_mgr == 'apt'"

- name: Ensure reboot-if-needed is run overnight
  cron:
    name: "Reboot if needed"
    user: "root"
    minute: "0"
    hour: "3"
    job: "/root/reboot-if-needed.sh"
  when: "'headless' in group_names and ansible_pkg_mgr == 'apt'"

- name: Add a non-root user
  user: name={{admin_user}} groups={{sudo_group}} append=true shell=/usr/bin/zsh
  register: base_user

- name: Disable SSH password logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: #?PasswordAuthentication.*
    line: PasswordAuthentication no

- name: Ensure SSH trafic is limited through firewall
  tags: ['ufw']
  ufw:
    rule: limit
    port: 'ssh'

- name: Ensure UWF uses a default deny policy
  tags: ['ufw']
  ufw:
    state: enabled
    policy: deny

