---
- name: Update all apt packages to the latest version
  apt: upgrade=dist update_cache=yes
  when: ansible_os_family == "Debian"

- name: Ensure local bin directory exists
  file:
    dest: /home/{{admin_user}}/.local/bin
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"

- name: Add Arch upgrade script
  copy:
    src: upgrade.sh
    dest: /home/{{admin_user}}/.local/bin/upgrade.sh
    mode: 0755
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
  when: ansible_os_family == "Archlinux"

- name: Add a non-root user
  user: name={{admin_user}} groups={{sudo_group}} append=true shell=/usr/bin/zsh
  register: base_user

- name: Disable SSH password logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: #?PasswordAuthentication.*
    line: PasswordAuthentication no

