---
- name: Clone dotfiles repository
  remote_user: "{{username}}"
  git: repo=git@github.com:{{github_user}}/dotfiles.git dest=/home/{{username}}/dotfiles
  ignore_errors: yes

- name: Bootstrap dotfiles
  remote_user: "{{username}}"
  command: /home/{{username}}/dotfiles/bootstrap.sh -f creates=/home/{{username}}/.zshrc
  args:
    creates: /home/{{username}}/.commonrc

