---
- name: Clone dotfiles repository
  remote_user: "{{user}}"
  git: repo=git@github.com:{{github_user}}/dotfiles.git dest=/home/{{user}}/dotfiles
  ignore_errors: yes

- name: Bootstrap dotfiles
  remote_user: "{{user}}"
  command: /home/{{user}}/dotfiles/bootstrap.sh -f creates=/home/{{user}}/.zshrc
  args:
    creates: /home/{{user}}/.commonrc

