---

- name: Read SSH public key to authorize
  shell: cat /home/{{username}}/.ssh/id_rsa.pub
  register: github_ssh_pub_key

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "{{inventory_hostname}}"
    token: "{{github_token}}"
    pubkey: '{{ github_ssh_pub_key.stdout }}'

- name: Clone dotfiles repository
  become: yes
  become_user: "{{username}}"
  git: repo=git@github.com:{{github_user}}/dotfiles.git dest=/home/{{username}}/dotfiles
  ignore_errors: yes

- name: Bootstrap dotfiles
  become: yes
  become_user: "{{username}}"
  command: /home/{{username}}/dotfiles/bootstrap.sh -f creates=/home/{{username}}/.zshrc
  args:
    creates: /home/{{username}}/.commonrc

