---
- include_tasks: utils.yml

- name: Ensure user exists
  user: name={{username}} shell=/usr/bin/zsh

- name: Ensure mosh traffic is allowed through the firewall
  tags: ['ufw']
  ufw:
    rule: allow
    port: '60000:61000'
    proto: 'udp'

- include_tasks: vim.yml
- include_tasks: dotfiles.yml
- include_tasks: capslock.yml

