- name: "Ensure public key is present"
  copy:
    src: ssh/{{user}}/{{inventory_hostname}}/id_rsa.pub
    dest: /home/{{user}}/.ssh/id_rsa.pub
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0644

- name: "Ensure private key is present"
  copy:
    src: ssh/{{user}}/{{inventory_hostname}}/id_rsa
    dest: /home/{{user}}/.ssh/id_rsa
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600

- name: "Ensure hosts are authorized"
  lineinfile:
    path: /home/{{user}}/.ssh/authorized_keys
    line: "{{lookup('file', 'ssh/{{user}}/{{item}}/id_rsa.pub')}}"
    create: true
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600
  with_items: "{{authorized_hosts}}"

