---
- name: "Ensure .ssh directory exists"
  file:
    state: directory
    name: "/home/{{user}}/.ssh"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0700

- name: "Ensure public key is present"
  copy:
    src: ssh/{{user}}/{{inventory_hostname}}/id_rsa.pub
    dest: /home/{{user}}/.ssh/id_rsa.pub
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0644

- name: "Ensure private key is present"
  copy:
    src: ssh/{{user}}/{{inventory_hostname}}/id_rsa
    dest: /home/{{user}}/.ssh/id_rsa
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600

- name: "Ensure hosts are authorized"
  authorized_key:
    user: "{{user}}"
    key: "{{lookup('file', 'ssh/{{user}}/{{item}}/id_rsa.pub')}}"
  with_items: "{{authorized_hosts}}"

